### PR TITLE
Add recaptcha to signup form

### PR DESCRIPTION
**Pull request by sethvargo**
/cc @KFishner

### CODE REVIEW

**Comment by sethvargo** [comment]
We don't get a lot of customizations around the styling sadly.

screen shot 2016-01-04 at 12 10 39 pm

**Comment by KFishner** [comment]
Yeah that styling is sad. @pearkes might have issues with it but I'm ok if that's the best option.

**Comment by sethvargo** [comment]
There's "dark" and "light". Sadly those are the only choices outside of rolling our own (which is probably not economical). Here's what "light" looks like:

screen shot 2016-01-04 at 12 20 15 pm


http://stackoverflow.com/questions/27713505/recaptcha-api-v2-styling

**Comment by KFishner** [comment]
Dark is less offensive IMO

**Comment by pearkes** [comment]
How do we verify the recaptcha server side? I looked into this and we'd have to proxy the request to do it right. Or are we just hoping it will discourage them?

**Comment by sethvargo** [comment]
Since we submit directly to salesforce, we have to do this: https://developer.salesforce.com/page/Adding_CAPTCHA_to_Force.com_Sites.

I was just going to implement the client side validation for now and then see if the bots decrease in submissions. If they don't we can implement the server-side validation.

**Comment by KFishner** [comment]
@sethvargo @pearkes can this be deployed?

**Comment by sethvargo** [comment]
Gonna deploy for now and then see if we need the server-side verification

**Pull request merged**
