### PR TITLE
Add social links

### PR DESCRIPTION
**Pull request by sethvargo**
/cc @KFishner @janaboruta

### CODE REVIEW

**Comment by pearkes** [comment]
We do have twitter/github on the left side, and I worry about pointing people to all these things when we don't really update them. Maybe do youtube/shop under those existing icons?

**Comment by KFishner** [comment]
+1 @pearkes idea

**Comment by sethvargo** [comment]
@pearkes we have to add youtube and google+ for verification reasons, even if we never update them :frowning:. I can move them over, but then things feel unbalanced to me:

screen shot 2016-02-03 at 3 39 34 pm
screen shot 2016-02-03 at 3 40 07 pm

I also never even noticed the twitter and github on the left side.

**Comment by KFishner** [comment]
Ok I like it better with the social header @sethvargo

**Comment by pearkes** [comment]
@sethvargo Cool, I'm ok with the header still not sure about google+/fb, what verification do you mean? Just don't want to send them to a ghost town

**Pull request merged**
